# Travis-CI.org build script

# container-based infrastructure
sudo: false
# need APT packages to get white-listed first;

# python-mock:
# https://github.com/travis-ci/apt-package-whitelist/issues/1081

# python-pyfits:
# https://github.com/travis-ci/apt-package-whitelist/issues/1082

#sudo: required

# install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev python-sphinx sphinx-common python-matplotlib python-scipy python-mock python-pyfits
#   - sudo pip install numpydoc

install:
   - pip install --user numpydoc
   - pip install --user pyfits
   - ls ~/.local

# python-numpydoc -- not available until Ubuntu 14.04 trusty

language: c
compiler:
  - gcc
#  - clang


before_script:
    - export NETPBM_INC="-I$(pwd)"
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - pkg-config --exists gsl
    - pkg-config --modversion gsl
    - ls /usr/include/wcslib*
    - pwd
    - echo $HOME
    - ls $HOME
    - ls $HOME/astrometry.net
    - set
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git; cd astrometry.net; ln -sf /usr/include netpbm; make && make py); fi
    - (cd $HOME/astrometry.net && git pull && make && make py)
    - ln -s $HOME/astrometry.net astrometry

# Clean Astrometry.net cache?
#    - (cd $HOME; rm -R astrometry.net; git clone https://github.com/dstndstn/astrometry.net.git; cd astrometry.net; ln -sf /usr/include netpbm)

#    - export SYSTEM_GSL=yes
#    - if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
#    - (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
#    - ln -s $HOME/fitsio/lib/python/fitsio .

script:
    - pwd
    - ls
    - echo $HOME
    - ls -al $HOME
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)
    - echo "$PYTHONPATH"
    - ls -l
    - python -c "import sys; print '\n'.join(sys.path)"
    - pwd
    - make
    - make doc
    - python test/test_tractor.py

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - python-numpy
    - swig
    - gsl-bin
    - libgsl0-dev
    - python-sphinx
    - sphinx-common
    - python-scipy
    - python-matplotlib
    - python-tk

#    - python-mock
#    - python-pyfits
#    - python-numpydoc

cache:
  directories:
  - $HOME/cache/.pip
  - $HOME/astrometry.net

#  - $HOME/fitsio-git
