# Travis-CI.org build script

# We use the container-based infrastructure
# http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04.5 LTS
dist: trusty

# python versions to test against...
language: python
python:
  - "2.7"
  - "3.6"

install:
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install numpydoc
    - pip install Sphinx
    - pip install coveralls
    - pip install pycodestyle
    - pip install fitsio
    # fitsio master version?
    # - pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git#egg=fitsio

    - export WCSLIB_INC="-I/usr/include/wcslib-4.20"
    - export WCSLIB_LIB="-lwcs"
    - export SYSTEM_GSL=yes
    - export NETPBM_INC="-I$(pwd)"
    - pip install -v --no-deps --upgrade git+https://github.com/dstndstn/astrometry.net
    # - python -c "import astrometry; print(astrometry.__file__)"
    # - python -c "import os; import astrometry; d=os.path.dirname; print(d(d(d(d(d(astrometry.__file__))))))"
    # - echo $PATH
    # - ls ~/virtualenv/
    # - ls ~/virtualenv/python*
    # - ls ~/virtualenv/python*/bin
    # - which fitsverify

script:
    - python --version
    - python setup.py install
    - python setup.py build_ext --inplace
    - make doc
    - echo $PYTHONPATH
    - coverage erase

    # Coverage doesn't seem to like measuring the coverage of
    # installed code (or, at least, we haven't told it we care about
    # the installed code in .coveragerc), so try to run w/ code in
    # current dir.  Also need to ensure that CWD is ahead of the
    # installed code in PYTHONPATH.
    - export PYTHONPATH=$(pwd):${PYTHONPATH}
    #- export COVERAGE_FILE=$(pwd)/.coverage
    #- export COVERAGE_RC=$(pwd)/.coveragerc
    #- export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
    - coverage run test/test_psfex.py
    #- coverage report
    - coverage run -a test/test_sdss.py
    #- coverage report
    - coverage run -a test/test_tractor.py
    #- coverage report
    - coverage run -a test/test_galaxy.py
    #- coverage report
    - coverage run -a tractor/mixture_profiles.py
    #- coverage report
    - export SDSS_DATA=$(pwd)/test/data-sdss
    - coverage run -a examples/tractor-sdss-synth.py --roi 0 100 0 100 --run 1000 --camcol 1 --field 100 --band r --sdss-dir ${SDSS_DATA} --const-invvar --no-flipbook
    #- coverage report
    - coverage run -a examples/mini.py
    #- coverage report
    - coverage run -a examples/decam-refit.py
    - coverage report
    - pycodestyle --show-source tractor/ wise/

after_success:
    - coveralls

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev

cache:
  directories:
  - $HOME/cache/.pip
  # pip install --local goes here:
  - $HOME/.local
