# Travis-CI.org build script

# We use the container-based infrastructure
# http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# "trusty" is Ubuntu 14.04.5 LTS
dist: trusty

# python versions to test against...
language: python
python:
  - "2.7"
  - "3.6"

install:
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install numpydoc
    #- pip install astropy
    #- pip install photutils
    - pip install Sphinx
    - pip install coveralls
    - pip install fitsio
    # fitsio master version?
    # - pip install --no-deps --upgrade git+https://github.com/esheldon/fitsio.git#egg=fitsio

before_script:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.20"
    - export WCSLIB_LIB="-lwcs"
    - export SYSTEM_GSL=yes
    - export NETPBM_INC="-I$(pwd)"

    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git; cd astrometry.net; ln -sf /usr/include netpbm; make && make py); fi
    - (cd $HOME/astrometry.net && git pull && make && make py) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git && cd astrometry.net && make && make py)
    - ln -s $HOME/astrometry.net astrometry
    #- export PATH=${PATH}:~/astrometry.net/blind/

script:
    - export PYTHONPATH=${PYTHONPATH}:$HOME/astrometry.net
    - python setup.py build_ext --inplace
    - find . -name "*.so"
    # ??
    - python setup.py install
    - make doc
    - echo $PYTHONPATH
    - python -c "import sys; print(sys.path)"
    - python -c "import tractor; print(tractor.__file__)"
    - python -c "import tractor.emfit; print(tractor.emfit.__file__)"
    - coverage erase
    - coverage run test/test_psfex.py
    - coverage run -a test/test_sdss.py
    - coverage run -a test/test_tractor.py
    - coverage run -a test/test_galaxy.py
    - coverage run -a tractor/mixture_profiles.py
    - coverage run -a examples/tractor-sdss-synth.py --roi 0 100 0 100 --run 1000 --camcol 1 --field 100 --band r --sdss-dir test/data-sdss --const-invvar --no-flipbook
    - coverage run -a examples/mini.py

after_success:
    - coveralls

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev

cache:
  directories:
  - $HOME/astrometry.net

# python-mock:
# https://github.com/travis-ci/apt-package-whitelist/issues/1081

# python-pyfits:
# https://github.com/travis-ci/apt-package-whitelist/issues/1082

# python-numpydoc -- not available until Ubuntu 14.04 trusty
# (currently Travis-CI uses 12.x precise)

cache:
  directories:
  - $HOME/cache/.pip
  - $HOME/astrometry.net
  # pip install --local goes here:
  - $HOME/.local
