# Travis-CI.org build script

# We use the container-based infrastructure
# http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
sudo: false

# Use these APT packages once they are white-listed:

# python-mock:
# https://github.com/travis-ci/apt-package-whitelist/issues/1081

# python-pyfits:
# https://github.com/travis-ci/apt-package-whitelist/issues/1082

# python-numpydoc -- not available until Ubuntu 14.04 trusty
# (currently Travis-CI uses 12.x precise)

install:
   - pip install --user numpy==1.11.0
   - pip install --user numpydoc
   # - pip install --user pyfits
   # For sdss.common
   - pip install --user astropy
   - pip install --user coveralls
   - pip install --user fitsio
   - ls ~/.local

language: c
compiler:
  - gcc
#  - clang


before_script:
    - export NETPBM_INC="-I$(pwd)"
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - export SYSTEM_GSL=yes
    - pkg-config --exists gsl
    - pkg-config --modversion gsl
    - ls /usr/include/wcslib*
    - pwd
    - echo $HOME
    - ls $HOME
    - ls $HOME/astrometry.net
    - set
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git; cd astrometry.net; ln -sf /usr/include netpbm; make && make py); fi
    - (cd $HOME/astrometry.net && git pull && make && make py) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git && cd astrometry.net && make && make py)
    - ln -s $HOME/astrometry.net astrometry
    - export PATH=${PATH}:~/astrometry/blind/

# Clean Astrometry.net cache?
#    - (cd $HOME; rm -R astrometry.net; git clone https://github.com/dstndstn/astrometry.net.git; cd astrometry.net; ln -sf /usr/include netpbm)

#    - if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
#    - (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
#    - ln -s $HOME/fitsio/lib/python/fitsio .

script:
    - pwd
    - ls
    - echo $HOME
    - ls -al $HOME
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)
    - echo "$PYTHONPATH"
    - ls -l
    - python -c "import sys; print '\n'.join(sys.path)"
    - python -c "import numpy; print numpy.__file__"
    - pwd
    - make
    - make doc
    - coverage run test/test_psfex.py
    - coverage run test/test_tractor.py
    - coverage run examples/tractor-sdss-synth.py --roi 100 200 100 200 --no-flipbook

after_success:
    #- coveralls debug
    - coveralls

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev
    - python-sphinx
    - sphinx-common
    - python-scipy
    - python-matplotlib
    - python-tk

#    - python-numpy
#    - python-mock
#    - python-pyfits
#    - python-numpydoc

cache:
  directories:
  - $HOME/cache/.pip
  - $HOME/astrometry.net
  # pip install --local goes here:
  - $HOME/.local


#  - $HOME/fitsio-git
