# This file is part of the tractor-spherex fork of the Tractor
# (https://github.com/Caltech-IPAC/tractor-spherex), created for the NASA SPHEREx
# mission's use by the SPHEREx Science Data Center team at Caltech/IPAC.
#
# Copyright (C) 2025-2026, California Institute of Technology.
# Licensed under the GNU General Public License, version 2 (GPLv2),
# the same as the Tractor. See LICENSE/COPYING.
#
# This file adds the ability to use recent versions of pip install.

[build-system]
requires = ["setuptools>=64", "setuptools_scm", "wheel", "numpy", "opencv-python-headless"]
build-backend = "setuptools.build_meta"

[project]
name = "tractor"
authors = [
    {name = "Dustin Lang", email = "dstndstn@gmail.com"},
    {name = "David W. Hogg"},
]
dynamic = ["version"]
dependencies = [
    "numba",
    "numpy",
    "opencv-python-headless"
]

[tools.setuptools_scm]
